# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

# file will be generated by setuptools-scm at a future time
# when that happens, avoid changing, and don't track in version control

__all__ = ["__version__", "__version_tuple__", "version", "version_tuple"]

TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple
    from typing import Union

    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.0.post4+g0024c3f.d20250508"
__version_tuple__ = version_tuple = (0, 0, "post4", "g0024c3f.d20250508")

