[envs.default]
pre-install-commands = [
  "pip install -r requirements-testing.txt"
]

[envs.default.scripts]
sync = "pip install -r requirements-testing.txt"
test = "pytest --cov=vred_submitter --cov-config pyproject.toml {args:test/unit} && pytest --no-cov {args:test/test_copyright_headers.py}"
test-installer = "pytest --no-cov {args:test/installer} -vvv"
typing = "mypy {args:src test}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]

[[envs.all.matrix]]
python = ["3.11", "3.12"]

[envs.default.env-vars]
SKIP_BOOTSTRAP_TEST_RESOURCES="True"

[envs.codebuild.scripts]
build = "hatch build"

[envs.integ]
pre-install-commands = [
  "pip install -r requirements-integ-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.unit]
pre-install-commands = [
  "pip install -r requirements-unit-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.worker]
pre-install-commands = [
  "pip install -r requirements-worker-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.integ.scripts]
test = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1"
test_submitters = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m submitter"

[envs.unit.scripts]
test = "pytest --cov=vred_submitter --cov-config pyproject.toml {args:test/unit} -vvv"

[envs.worker.scripts]
test = "pytest --no-cov {args:test/worker} -vvv --numprocesses=1"
test_submitters = "pytest --no-cov {args:test/worker} -vvv --numprocesses=1 -m submitter"

[envs.codebuild.env-vars]
SKIP_BOOTSTRAP_TEST_RESOURCES="True"

[envs.release]
detached = true

[envs.installer.scripts]
build-installer = "python {root}/scripts/build_installer_cli.py --installer-source-path {root}/installer/DeadlineCloudForVREDSubmitter.xml {args:}"

