[envs.default]
pre-install-commands = [
  "pip install -r requirements-testing.txt"
]

[envs.default.scripts]
sync = "pip install -r requirements-testing.txt"
test = "pytest --cov=vred_submitter --cov-config pyproject.toml {args:test/unit} && pytest --no-cov {args:test/test_copyright_headers.py}"
test-installer = "pytest --no-cov {args:test/installer} -vvv"
typing = "mypy {args:src test}"
style = [
  "ruff check {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "style",
]
lint = [
  "style",
  "typing",
]

[[envs.all.matrix]]
python = ["3.11", "3.12"]

[envs.unit]
pre-install-commands = [
  "pip install -r requirements-unit-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.submitter]
pre-install-commands = [
  "pip install -r requirements-submitter-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.worker]
pre-install-commands = [
  "pip install -r requirements-worker-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.integ]
pre-install-commands = [
  "pip install -r requirements-submitter-testing.txt",
  "pip install -r requirements-worker-testing.txt",
  "pip install -r requirements-testing.txt"
]

[envs.unit.scripts]
test = "pytest --cov=vred_submitter --cov-config pyproject.toml {args:test/unit} -vvv"

[envs.integ.scripts]
test = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1"
test_integ = "pytest --no-cov {args:test/integ} -vvv --numprocesses=1 -m integ"

[envs.integ-ci]
pre-install-commands = [
  "pip install -r requirements-submitter-testing.txt",
  "pip install -r requirements-worker-testing.txt",
  "pip install -r requirements-testing.txt"
]

[[envs.integ-ci.matrix]]
vred = ["2025"]

[[envs.integ-ci.matrix]]
vred = ["2026"]

[envs.integ-ci.overrides]
matrix.vred.env-vars = [
  { key = "VREDPRO", value = "C:\\Program Files\\Autodesk\\VREDPro-17.3\\bin\\WIN64\\VREDPro.exe", if = ["2025"] },
  { key = "VREDPRO", value = "C:\\Program Files\\Autodesk\\VREDPro-18.0\\bin\\WIN64\\VREDPro.exe", if = ["2026"] },
]

[envs.integ-ci.env-vars]
VRED_VERSION = "{matrix:vred}"

[envs.integ-ci.scripts]
setup = "python ./pipeline/setup-runner.py --versions {matrix:vred} {args}"
test = "pytest --no-cov {args:test/integ} -vvv -p no:xdist -s"

[envs.codebuild.env-vars]
SKIP_BOOTSTRAP_TEST_RESOURCES="True"

[envs.release]
detached = true

[envs.release.scripts]
deps = "pip install -r requirements-release.txt"
bump = "semantic-release -v --strict version --no-push --no-commit --no-tag --skip-build {args}"
version = "semantic-release -v --strict version --print {args}"

[envs.installer.scripts]
build-installer = "python {root}/scripts/build_installer_cli.py --installer-source-path {root}/installer/DeadlineCloudForVREDSubmitter.xml {args:}"

