name: "Release: Publish"
run-name: "Release: ${{ github.event.head_commit.message || inputs.tag }}"

on:
  push:
    branches:
      - mainline
    paths:
      - CHANGELOG.md
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: Specify a tag to re-run a release.

concurrency:
  group: release

permissions:
  contents: read

jobs:
  TagRelease:
    uses: aws-deadline/.github/.github/workflows/reusable_tag_release.yml@mainline
    secrets: inherit
    with:
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || '' }}

  UnitTests:
    needs: [TagRelease]
    name: Unit and Integration Tests
    uses: ./.github/workflows/code_quality.yml
    with:
      tag: ${{ needs.TagRelease.outputs.tag }}

  PreRelease:
      needs: [TagRelease, UnitTests]
      uses: aws-deadline/.github/.github/workflows/reusable_prerelease.yml@mainline
      permissions:
        id-token: write
        contents: write
      secrets: inherit
      with:
          tag: ${{ needs.TagRelease.outputs.tag }}

  Release:
      needs: [TagRelease, PreRelease]
      uses: aws-deadline/.github/.github/workflows/reusable_release.yml@mainline
      secrets: inherit
      permissions:
        id-token: write
        contents: write
      with:
          tag: ${{ needs.TagRelease.outputs.tag }}
  
  Publish:
      needs: [TagRelease, Release]
      uses: aws-deadline/.github/.github/workflows/reusable_publish_python.yml@mainline
      permissions:
        id-token: write
      secrets: inherit
      with:
          tag: ${{ needs.TagRelease.outputs.tag }}

  # PyPI does not support reusable workflows yet
  # # See https://github.com/pypi/warehouse/issues/11096
  PublishToPyPI:
    # Skip until the repository is public
    if: ${{ false }}
    needs: Publish
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.Publish.outputs.tag }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade hatch
      - name: Build
        run: hatch -v build
      # # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
