name: Contributor Responded
on:
    issue_comment:
        types: [created, edited]

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
    check-for-response:
        uses: aws-deadline/.github/.github/workflows/reusable_responded.yml@mainline
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
